Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/wily64'

  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.network :private_network, ip: "192.168.222.150"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end

  config.ssh.forward_agent = true

  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
  config.vm.provision "file", source: "~/.gitignore_global", destination: ".gitignore_global"
  config.vm.provision :shell, path: 'vagrant_bootstrap.sh', keep_color: true  

end